// <auto-generated />
using System;
using Asp.NetCore.MVC.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asp.NetCore.MVC.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230616071229_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableIncident", b =>
                {
                    b.Property<int>("IncidentNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentNumber"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DbTableIncidentFromId")
                        .HasColumnType("int");

                    b.Property<int>("DbTableReasonTitleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EditingDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentNumber");

                    b.HasIndex("DbTableIncidentFromId");

                    b.HasIndex("DbTableReasonTitleId");

                    b.ToTable("DbTableIncidents");
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableIncidentFrom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EditingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DbTableIncidentFroms");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            EditingDate = new DateTime(2023, 6, 16, 12, 12, 29, 181, DateTimeKind.Local).AddTicks(3265),
                            From = "Колл-центр"
                        },
                        new
                        {
                            Id = 2,
                            EditingDate = new DateTime(2023, 6, 16, 12, 12, 29, 181, DateTimeKind.Local).AddTicks(3268),
                            From = "Сервисный центр"
                        },
                        new
                        {
                            Id = 1,
                            EditingDate = new DateTime(2023, 6, 16, 12, 12, 29, 181, DateTimeKind.Local).AddTicks(3289),
                            From = "Все источники"
                        });
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableIncidentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IncidentNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("DbTableIncidentHistories");
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableReasonTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EditingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DbTableReasonTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EditingDate = new DateTime(2023, 6, 16, 12, 12, 29, 181, DateTimeKind.Local).AddTicks(3230),
                            Reason = "Все причины"
                        },
                        new
                        {
                            Id = 2,
                            EditingDate = new DateTime(2023, 6, 16, 12, 12, 29, 181, DateTimeKind.Local).AddTicks(3232),
                            Reason = "Тестовая причина"
                        });
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EditingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DbTableUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("65c9c733-2d13-4f40-8ed4-05a148087036"),
                            EditingDate = new DateTime(2023, 6, 16, 12, 12, 29, 181, DateTimeKind.Local).AddTicks(3071),
                            FirstName = "Admin",
                            IsAdministrator = true,
                            LastName = "Admin",
                            Login = "admin",
                            Password = "admin"
                        });
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableIncident", b =>
                {
                    b.HasOne("Asp.NetCore.MVC.Domain.Models.Tables.DbTableIncidentFrom", "IncFrom")
                        .WithMany("Incidents")
                        .HasForeignKey("DbTableIncidentFromId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Asp.NetCore.MVC.Domain.Models.Tables.DbTableReasonTitle", "IncReason")
                        .WithMany("Incidents")
                        .HasForeignKey("DbTableReasonTitleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncFrom");

                    b.Navigation("IncReason");
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableIncidentFrom", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Asp.NetCore.MVC.Domain.Models.Tables.DbTableReasonTitle", b =>
                {
                    b.Navigation("Incidents");
                });
#pragma warning restore 612, 618
        }
    }
}
